### PR TITLE
Updated Phore logos

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by meyer9 — APPROVED** [review]
thanks for the contribution

**Comment by meyer9** [comment]
if you have GPG, can you sign your commit?

**Comment by ghost** [comment]
Signed.

**Comment by meyer9** [comment]
one more thing - can you switch the base branch to development? thanks!

**Comment by meyer9** [comment]
Merged in https://github.com/phoreproject/Phore/commit/0503d439f7483e5ce12394ac542184f63a3ada5a

**Pull request closed without merging**
