### PR TITLE
[PHR-8] Added select coin strategy. Sorting coins by amount if the transaction size is too large

### PR DESCRIPTION
**Pull request by wqking**
Please review.

Added new param to CreateTransaction to give it better controll. Added strategy to select coins.
Now if the transaction size is too large, CreateTransaction will try again by sorting the coins by amount (for less inputs).

Not tested yet. If we want to test it, we need to write Python integration test for it, let me know if we need to do it.

### CODE REVIEW

**Comment by tohsnoom** [comment]
Yes, please write tests for this. My initial feedback is that it looks like it probably solves the issue.

I looked at the latest bitcoin core and they seem to have a more sophisticated algorithm for coin selection (actually two algorithms--Branch and Bound is one, and Knapsack Solver is the other), but I don't think that is needed at this time--it is optimized around fee minimization and tries a bunch of combinations to find the best coin selection set, and that complexity is probably needed more for bitcoin since fees are a much bigger issue for bitcoin than for Phore. Our fees are miniscule in comparison to bitcoin. In the future we may want to look at pulling those in, but it would probably make sense to look at pulling in other bitcoin core upstream first.

**Comment by wqking** [comment]
I will add some Python tests for it.
With the newly added strategy mechanism, it should be easy to add new coin selection algorithms in the future.

**Comment by wqking** [comment]
Added Python test, and did some fix according to the test.

**Review by tohsnoom — APPROVED** [review]

**Comment by tohsnoom** [comment]
Merged to branch rel-1.6.4.

**Pull request closed without merging**
