### PR TITLE
Fixed the bug in makefile

### PR DESCRIPTION
**Pull request by KolbyML**

### CODE REVIEW

**Comment by meyer9** [comment]
this breaks the make depends system
https://travis-ci.org/phoreproject/Phore/jobs/440718358#L1211

**Comment by KolbyML** [comment]
This doesn't this fixes it

**Comment by KolbyML** [comment]
Travis is broken from something else this fixes syntax and that is all

**Comment by mrmetech** [comment]
Look at the master branch already etc this runs longer

**Review by tohsnoom — APPROVED** [review]

**Pull request merged**
